collection_layers: [host]
contributors: [Jose Rodriguez @Cyb3rPandaH]
data_components:
- name: service creation
  relationships:
  - {relationship: created, source_data_element: user, target_data_element: service}
  type: activity
definition: Information about software programs that run in the background and typically
  start with the operating system.
name: Service
platforms: [Windows]
references: ['https://docs.microsoft.com/en-us/dotnet/framework/windows-services/introduction-to-windows-service-applications',
  'https://www.linux.com/news/introduction-services-runlevels-and-rcd-scripts/']
